name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - develop
    exclude:
      - release/xyz	
  paths:
    exclude:
      - README.md
pr:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- checkout: self  
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure Pass - Sponsorship(9604d4da-f16c-4b80-ac1b-34bd71a69ed3)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az --version
      az account show
    addSpnToEnvironment: true

- script: |
    echo Terraform init
    terraform init
  displayName: 'Terraform init'
- script: |
    echo Terraform validate
    terraform validate
  displayName: 'Terraform validate'

- script: |
    az login 
    echo Terraform plan
    terraform plan
  displayName: 'Terraform plan'

- script: |
    echo Terraform apply
    terraform apply -auto-approve
  displayName: 'Terraform apply'
